# Generated by Django 2.2.6 on 2019-11-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_auto_20191129_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='s', upload_to=''),
        ),
    ]
