# Generated by Django 2.2.6 on 2019-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0012_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
