# Generated by Django 2.2.6 on 2019-12-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0016_auto_20191206_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
