# Generated by Django 2.2.6 on 2019-12-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0017_auto_20191206_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(),
        ),
    ]
